name: localtunnel-lucasrangit
version: '1.8.3'
summary: localtunnel exposes your localhost to the world for easy testing and sharing!
description: |
  localtunnel exposes your localhost to the world for easy testing and
  sharing!
  No need to mess with DNS or deploy just to have others test out your
  changes.
  Great for working with browser testing tools like browserling or external
  api callback services like twilio which require a public url for callbacks.

grade: stable
confinement: strict

apps:
  node-service:
    command: bin/lt --port "\"$(awk '/^port/{print $2}' \"$SNAP_DATA/$SNAP_NAME.conf\")\"" "\"$(awk '/^host/{print \"--host \"$2}' \"$SNAP_DATA/$SNAP_NAME.conf\")\"" "\"$(awk '/^subdomain/{print \"--subdomain \"$2}' \"$SNAP_DATA/$SNAP_NAME.conf\")\"" "\"$(awk '/^local-host/{print \"--local-host \"$2}' \"$SNAP_DATA/$SNAP_NAME.conf\")\""
    daemon: simple
    restart-condition: always
    plugs: [network-bind]

parts:
  webserver:
    source: https://github.com/robotnyc/localtunnel.git
    plugin: nodejs
